#:schema node_modules/wrangler/config-schema.json
name = "meal-mate-shop"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

d1_databases = [
  { binding = "DB", database_name = "meal-mate-db", database_id = "d8beed67-f108-4a73-b184-815fc0fb1100" }
]

[env.production]
binding = "DB"
database_name = "meal-mate-db"
database_id = "d8beed67-f108-4a73-b184-815fc0fb1100"

[dev]
port = 3000
local_protocol = "http"

