#:schema node_modules/wrangler/config-schema.json
name = "meal-mate-shop"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public" # 이 경로가 public이어야 html들이 배포됩니다.

[[d1_databases]]
binding = "DB" # 코드 내에서 데이터베이스에 접근할 때 쓰는 이름
database_name = "meal-mate-db"
database_id = "여러분의-D1-ID-복사해서-여기에-넣으세요"
